import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="pt-br" translate="no">
      <body className="bg-gray-800 text-white">
        {/* header */}
        <Header />

        {/* main */}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
