import "./globals.css";
import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <html>
      <body className="min-h-screen bg-black text-white">
        <h1>Primeiro projeto</h1>
        <hr />

        <div>
          {children}
        </div>
      </body>
    </html>
  )
}

export default Layout;