// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evvalqijcwdlozmzbxcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dmFscWlqY3dkbG96bXpieGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTkyNjQsImV4cCI6MjA3NjI3NTI2NH0._c8ak2dKmcaLry6KqnObtKavaXYdE3CKXyei4-tuy5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});