import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RoomLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RoomLayoutProps) {
  return (
    <html lang="pt-br" translate="no">
      <body className="w-full min-h-screen bg-gray-800 flex flex-col">
        {children}
      </body>
    </html>
  );
}
